### ISSUE TITLE
serveFile already add automatically the right mimetype, using file extension.

### ISSUE THREAD

**Issue by trikko** [aferust/servefolder#1]
Did I miss some ext?

https://github.com/aferust/servefolder/blob/b814ce6045b58852e367e7d102cf6a39fe7aa1db/source/app.d#L122

**Comment by aferust** [comment]
what did you mean? Sorry. It is ok with its present form of the code, right?

**Comment by aferust** [comment]
ahh i see, i will remove that redundant check, ok

**Comment by trikko** [comment]
I mean: that control is already done by Serverino, that adds the right mimetype automatically
